language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks

services:
  - mongodb

before_install:
  - gem install bundler -v '~> 1.10'

matrix:
  include:
    - rvm: jruby-9.1.6.0
      env: ORM=sequel JRUBY_OPTS="$JRUBY_OPTS --debug"
      gemfile: gemfiles/sequel.rb
